---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Сайт должен быть доступен на различных устройствах
implicit:
  -При переходе в корзину показывается список добавленных товаров и кнопка заказа товаров
  -Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  -В списке заказов отображаются оформленные заказы. Для каждого товара выводится его номер, дата, кнопка просмотра заказа 
